[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "sphinx-ansible-highlighter"
version = "0.1.0"
description = "Tools for building the Ansible Distribution"
authors = ["Felix Fontein <felix@fontein.de>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/ansible-community/antsibull"
packages = [
    { include = "sphinx_ansible_highlighter", from = "src" },
    { include = "tests", format = "sdist" }
]

[tool.poetry.plugins."pygments.lexers"]
Ansible-output = "sphinx_ansible_highlighter.pygments_lexer:AnsibleOutputLexer"
ansible-output = "sphinx_ansible_highlighter.pygments_lexer:AnsibleOutputLexer"

[tool.poetry.dependencies]
python = "^3.6.0"
pygments = ">= 2.6.1"
sphinx = { version = "*", optional = true }

[tool.poetry.extras]
sphinx = ["sphinx"]

[tool.poetry.dev-dependencies]
codecov = "*"
flake8 = ">= 3.8.0"
pylint = "*"
pytest = "*"
pytest-cov = "*"

[tool.isort]
line_length = 100
multi_line_output = 0
balanced_wrapping = true
